name: Deploy to server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: GuillaumeFalourd/setup-rsync@v1.2
        id: rsync
        with:
          ssh_key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          rsync -avzh -e "ssh -i ${{ steps.rsync.outputs.ssh_key_path }} -p 3367" . root@88.99.173.232:/opt/PharmaCoursor/
        
